### ISSUE TITLE
在 Android 7.1.2 之上调用 show 无效

### ISSUE THREAD

**Issue by drakeet** [kamikat/toast-compat#4]
你好，感谢开源和分享这个项目，但我发现在 Android 7.1.2 上 ToastCompat 无法弹出任何 toast，而在 Android 5.1.2 之上则正常，不知道能否修复。
谢谢！

**Comment by drakeet** [comment]
很可能与之有关的日志：

```java
12-08 18:42:41.647 1868-1868/system_process W/WindowManager: Attempted to remove non-existing token: android.os.Binder@88b1789
12-08 18:42:41.653 1868-3473/system_process W/WindowManager: Failed looking up window
 java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@15af38e does not exist
     at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9469)
     at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9460)
     at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2401)
     at com.android.server.wm.Session.remove(Session.java:202)
     at android.view.IWindowSession$Stub.onTransact(IWindowSession.java:242)
     at com.android.server.wm.Session.onTransact(Session.java:145)
     at android.os.Binder.execTransact(Binder.java:565)
```

**Comment by drakeet** [comment]
Debug 可得 WindowManager 内容大多为空：
![snip20171208_13](https://user-images.githubusercontent.com/5214214/33762627-2b038336-dc48-11e7-91b6-d7be509c070a.png)

**Comment by drakeet** [comment]
查看 Android Toast 源码可得，7.1 之后似乎必要传递一个 windowToken：
![image](https://user-images.githubusercontent.com/5214214/33763178-74198eb0-dc4a-11e7-9cae-d5efccd1d80b.png)

**Comment by drakeet** [comment]
我重新找到一个方法来修复 Android 7.1 带来的 Toast BadTokenException，该异常一直到 8.0 才被修复，因此我使用 hook 防止 BadTokenException 导致应用 crash：

https://github.com/drakeet/ToastCompat

**Comment by kamikat** [comment]
可否请教一下 Toast.show 函数到 SafeToastContext.addView 函数之间的调用栈呢？

**Comment by kamikat** [comment]
没有 Toast 弹出可能是因为 https://github.com/kamikat/toast-compat/blob/480076fb40885f7bef77a9f9f93c1a7e86a74501/src/main/java/moe/banana/support/ToastCompat.java#L327-L333 捕捉并忽略了异常。

**Comment by drakeet** [comment]
可能被捕捉了，但不应该这样，使用这个库在 Android 7.1 以上无论如何无法弹出任何 Toast。
